CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS;

USE DATABASE HEALTHCARE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS PUBLIC;

USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE ADMISSIONS (
    ADMISSION_ID STRING,
    PATIENT_ID STRING,
    WARD STRING,
    ADMISSION_DATETIME TIMESTAMP_NTZ,
    DISCHARGE_DATETIME TIMESTAMP_NTZ,
    ADMISSION_TYPE STRING,
    LENGTH_OF_STAY_DAYS FLOAT
);

CREATE OR REPLACE TABLE BED_OCCUPANCY (
    RECORD_ID STRING,
    DATE DATE,
    WARD STRING,
    BEDS_AVAILABLE INTEGER,
    BEDS_OCCUPIED INTEGER,
    OCCUPANCY_RATE FLOAT
);

CREATE OR REPLACE TABLE THEATRE_BOOKINGS (
    BOOKING_ID STRING,
    PATIENT_ID STRING,
    SURGERY_DATE DATE,
    SPECIALTY STRING,
    STATUS STRING,
    IS_CANCELLED BOOLEAN
);

CREATE OR REPLACE TABLE PATIENT_REFERRALS (
    REFERRAL_ID STRING,
    PATIENT_ID STRING,
    REFERRAL_SOURCE STRING,
    REFERRAL_DATE DATE,
    PRIORITY STRING,
    STATUS STRING
);
