USE DATABASE HEALTHCARE_ANALYTICS;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW VW_AVG_LENGTH_OF_STAY_BY_WARD AS
SELECT
    WARD,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 2) AS AVG_LENGTH_OF_STAY_DAYS,
    COUNT(*) AS TOTAL_ADMISSIONS
FROM ADMISSIONS
GROUP BY WARD;


CREATE OR REPLACE VIEW VW_BED_OCCUPANCY_BY_WARD AS
SELECT
    DATE,
    WARD,
    BEDS_AVAILABLE,
    BEDS_OCCUPIED,
    ROUND(OCCUPANCY_RATE * 100, 2) AS OCCUPANCY_PERCENTAGE
FROM BED_OCCUPANCY;


CREATE OR REPLACE VIEW VW_THEATRE_CANCELLATION_RATE AS
SELECT
    SURGERY_DATE,
    SPECIALTY,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(CASE WHEN IS_CANCELLED THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS,
    ROUND(AVG(CASE WHEN IS_CANCELLED THEN 1 ELSE 0 END) * 100, 2) AS CANCELLATION_PERCENTAGE
FROM THEATRE_BOOKINGS
GROUP BY SURGERY_DATE, SPECIALTY;


CREATE OR REPLACE VIEW VW_HOSPITAL_OPERATIONS_SUMMARY AS
SELECT
    A.WARD,
    COUNT(DISTINCT A.ADMISSION_ID) AS TOTAL_ADMISSIONS,
    ROUND(AVG(A.LENGTH_OF_STAY_DAYS), 2) AS AVG_LENGTH_OF_STAY_DAYS,
    ROUND(AVG(B.OCCUPANCY_RATE * 100), 2) AS AVG_OCCUPANCY_PERCENTAGE
FROM ADMISSIONS A
LEFT JOIN BED_OCCUPANCY B
    ON A.WARD = B.WARD
GROUP BY A.WARD;
